export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const PROFILES_REQUEST = 'PROFILES_REQUEST';
export const PROFILES_SUCCESS = 'PROFILES_SUCCESS';
export const PROFILES_FAILURE = 'PROFILES_FAILURE';
